### Register
POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"demouser1",
    "password":"Password1!",
    "email": "serverdeveloper@duck.com"
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "identifier": "demouser1",
    "password":"Password1!"
}

### Refresh Token
POST http://localhost:3000/refresh_tokens
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbW91c2VyMSIsIl9pZCI6IjY2ZWRhMmEwNzk3Mzk0YWNjZTY4MDhhYyIsImlhdCI6MTcyNjkxMTA1OSwiZXhwIjoxNzI5NTAzMDU5fQ.6MoF_bUxeh5KDkH81XIYgUTiKq11k54lBTz7a-Wmm_4"
}

### Search user
GET http://localhost:3000/users/search?username=demouser1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbW91c2VyMSIsIl9pZCI6IjY2ZWVhMzQ5NzdkMTZiODE1ZDdjMzE1MCIsImlhdCI6MTcyNjkyOTQ3MywiZXhwIjoxNzI5NTIxNDczfQ.32bOwCnigtcKQkWfNDkXU2w1U0cZKUByfy222mLj1N4

### Get User Chats
GET http://localhost:3000/users/chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbW91c2VyMSIsIl9pZCI6IjY2ZWVhMzQ5NzdkMTZiODE1ZDdjMzE1MCIsImlhdCI6MTcyNzU0MTI2NiwiZXhwIjoxNzMwMTMzMjY2fQ.T1zPqNyIPK7DnP-Ld2ZXQjjCruvhyHC_I_nTZcew-1o



### Get chat
GET http://localhost:3000/chats/66eee51b6f1c15754e1a1d7b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbW91c2VyMSIsIl9pZCI6IjY2ZWVhMzQ5NzdkMTZiODE1ZDdjMzE1MCIsImlhdCI6MTcyNzU0MTI2NiwiZXhwIjoxNzMwMTMzMjY2fQ.T1zPqNyIPK7DnP-Ld2ZXQjjCruvhyHC_I_nTZcew-1o

### Send Message
POST http://localhost:3000/chats/66eea34977d16b815d7c3150/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbW91c2VyMSIsIl9pZCI6IjY2ZWVhMzQ5NzdkMTZiODE1ZDdjMzE1MCIsImlhdCI6MTcyNjkzMTc4MCwiZXhwIjoxNzI5NTIzNzgwfQ.s9rGPlYZilZr5_4gKapJFCu40_qSjGYjUtGj7ZlFbtQ

{
    "content": "SGVsbG8gZ3V5cw==",
    "createdAt": "2024-09-21T09:29:35.267Z",
    "createdBy": "66eea34977d16b815d7c3150",
    "chatId": "66eea34977d16b815d7c3150"
}